name: felts
version: "0.1.0"
config-version: 2

profile: felts

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  felts:
    +materialized: view
    staging:
      +materialized: view
      coingecko:
        +schema: coingecko
      csv_import:
        +schema: csv_import
    marts:
      +materialized: table
      coingecko:
        +schema: coingecko
